### ISSUE TITLE
HttpOnly

### ISSUE THREAD

**Issue by Cubexp** [PuZhiweizuishuai/SpringSecurity-JWT-Vue-Deom#1]
大佬你好，我想问下，cookie设置了httpOnly，前端不可读取cookie里的数据了，那用户注销的问题解决怎么？

**Comment by PuZhiweizuishuai** [comment]
https://github.com/PuZhiweizuishuai/SpringSecurity-JWT-Vue-Deom/blob/fa6b09c92f1a96d8cb7d129fb6c6d4bae687a678/spring-security-jwt/src/main/java/com/bugaugaoshu/security/controller/LogoutController.java#L24

把token的value值设为null，覆盖掉，再传回去就行
