### ISSUE TITLE
疑问：类WebSecurityConfig方法configure(HttpSecurity http)

### ISSUE THREAD

**Issue by 549393092** [PuZhiweizuishuai/SpringSecurity-JWT-Vue-Deom#2]
请教一下，在类WebSecurityConfig的方法configure(HttpSecurity http)中，最后为什么不加入代码.sessionManagement().sessionCreationPolicy(SessionCreationPolicy.STATELESS)来实现无状态？

**Comment by PuZhiweizuishuai** [comment]
> 请教一下，在类WebSecurityConfig的方法configure（HttpSecurity http）中，最后为什么不加入代码.sessionManagement（）。sessionCreationPolicy（SessionCreationPolicy.STATELESS）来实现无状态？

我的锅，当时忘了，没想起来，现在加上了。
