### ISSUE TITLE
请教：Spring Security + JWT +Vue + History Mode浏览器刷新问题

### ISSUE THREAD

**Issue by 549393092** [PuZhiweizuishuai/SpringSecurity-JWT-Vue-Deom#3]
大神，
如果前端Vue-Router采用History Mode，当刷新浏览器时，URL总是会跳转到登录页面，请问在后端该如何处理？附上部分代码，请帮我看下，不甚感激。
```
public class SecurityConfig extends WebSecurityConfigurerAdapter{
  @Override
  protected void configure(HttpSecurity http) throws Exception {
    http.cors().and().csrf().disable().authorizeRequests().antMatchers("/login").permitAll()
      .anyRequest().authenticated();
    http.formLogin().loginPage("/login");
    http.addFilter(new JWTAuthenticationFilter(authenticationManager())) // 用户名，密码验证，验证成功会返回token给客户端
      .addFilter(new JWTAuthorizationFilter(authenticationManager()))
      .sessionManagement().sessionCreationPolicy(SessionCreationPolicy.STATELESS);
  }
}

public class JWTAuthorizationFilter extends BasicAuthenticationFilter {
  public JWTAuthorizationFilter(AuthenticationManager authenticationManager) {
    super(authenticationManager);
  }

  @Override
  protected void doFilterInternal(HttpServletRequest request, HttpServletResponse response, FilterChain chain) throws IOException, ServletException {
    String header = request.getHeader(Constant.REQUEST_HEADER_AUTH);
    // 问题出在这里，当（正常情况）调用rest api时，前端会把token带上，请求是合法的
    // 但是当刷新浏览器时，此时header = null，请求不合法，然后就会跳转到/login页面
    if (header == null || !header.startsWith(Constant.TOKEN_PREFIX)) {
      chain.doFilter(request, response);
      return;
    }

    UsernamePasswordAuthenticationToken authentication = getAuthentication(request);
    SecurityContextHolder.getContext().setAuthentication(authentication);
    chain.doFilter(request, response);
  }

  private UsernamePasswordAuthenticationToken getAuthentication(HttpServletRequest request) {
    String token = request.getHeader("Authorization");
    if (token != null) {
      // parse the token.
      String user = Jwts.parser().setSigningKey("secret").parseClaimsJws(token.replace("Bearer ", "")).getBody().getSubject();
      if (user != null) {
        return new UsernamePasswordAuthenticationToken(user, null, new ArrayList<>());
      }
      return null;
    }
    return null;
  }
```

**Comment by PuZhiweizuishuai** [comment]
我感觉你应该从前端解决这个问题，登陆信息需要保存在LocalStorage，保存在vuex里，刷新浏览器后数据会失效，所以可能会出现刷新后登陆失败的情况。

**Comment by 549393092** [comment]
谢谢！但还是有难点，请再帮我看下在前端如何实现。
比如我在登录页面www.api.com/test/login输入用户名密码后，后端会返回token给我，然后我把它保存到localStorage和vuex中，前端页面会跳转到主页面www.api.com/test，此时我点击菜单跳转到某主数据创建的初始页面www.api.com/test/init（通过vue-router跳转），然后我刷新页面，后端会接收到一个请求www.api.com/test/init，此时token为空。
我的问题是，页面刷新时前端怎样把存储的token赋到请求header上。

**Comment by PuZhiweizuishuai** [comment]
> 谢谢！但还是有难点，请再帮我看下在前端如何实现。
> 比如我在登录页面www.api.com/test/login输入用户名密码后，后端会返回token给我，然后我把它保存到localStorage和vuex中，前端页面会跳转到主页面www.api.com/test，此时我点击菜单跳转到某主数据创建的初始页面www.api.com/test/init（通过vue-router跳转），然后我刷新页面，后端会接收到一个请求www.api.com/test/init，此时token为空。
> 我的问题是，页面刷新时前端怎样把存储的token赋到请求header上。

登陆成功之后，直接把token写到http only的cookie里，只需要给前端返回登陆成功的用户信息和你需要的信息，然后保存就好，不需要返回token到localStorage里。这样就不需要把token放到header了，刷新也就没有问题了。

**Comment by PuZhiweizuishuai** [comment]
> 谢谢！但还是有难点，请再帮我看下在前端如何实现。
> 比如我在登录页面www.api.com/test/login输入用户名密码后，后端会返回token给我，然后我把它保存到localStorage和vuex中，前端页面会跳转到主页面www.api.com/test，此时我点击菜单跳转到某主数据创建的初始页面www.api.com/test/init（通过vue-router跳转），然后我刷新页面，后端会接收到一个请求www.api.com/test/init，此时token为空。
> 我的问题是，页面刷新时前端怎样把存储的token赋到请求header上。

```java
        Cookie cookie = new Cookie(COOKIE_TOKEN, jwt);
        cookie.setHttpOnly(true);
        cookie.setPath("/");
        cookie.setMaxAge(cookExpirationTime);
        response.addCookie(cookie);
```
这样前端做请求的时候，如果使用fetch api，那么就需要写credentials: "include" ，这是携带 Cookie 所必须的语句。不加这一句，fetch是不会携带cookie的

**Comment by 549393092** [comment]
再次感谢！我会先研究一下这种方法。我还有一个问题，因为即使是httponly的cookie也是有被盗用的风险，不知道你怎么认为？我看过vue-router官网关于history mode的文档，是说要在服务端（后端）处理而不是前端处理，我想试试看用nginx+tomcat组合的方式，nginx用来处理静态资源，比如www.api.com/test/init，然后真正的rest api call再diapatch给tomcat（spring mvc）来实现。不知道我是否理解的正确。

**Comment by PuZhiweizuishuai** [comment]
> 再次感谢！我会先研究一下这种方法。我还有一个问题，因为即使是httponly的cookie也是有被盗用的风险，不知道你怎么认为？我看过vue-router官网关于history mode的文档，是说要在服务端（后端）处理而不是前端处理，我想试试看用nginx+tomcat组合的方式，nginx用来处理静态资源，比如www.api.com/test/init，然后真正的rest api call再diapatch给tomcat（spring mvc）来实现。不知道我是否理解的正确。

没有绝对的安全，使用http only肯定是比放到本地安全的，一些知名的网站比如b站就是这么干的。
另一个，权限验证肯定是要放在后端的。nginx+tomcat也是对的
