### ISSUE TITLE
请教有关使用Vuex store的细节

### ISSUE THREAD

**Issue by SonHOuse1993** [PuZhiweizuishuai/SpringSecurity-JWT-Vue-Deom#5]
作者您好，在看你的代码的时候发现你的前端把服务器传回的数据放在了localStorage和store里。我觉得只存在localStorage就可以了吧？不知道Vuex的store存一份数据是有什么别的用途？谢谢大神！

**Comment by PuZhiweizuishuai** [comment]
> 作者您好，在看你的代码的时候发现你的前端把服务器传回的数据放在了localStorage和store里。我觉得只存在localStorage就可以了吧？不知道Vuex的store存一份数据是有什么别的用途？谢谢大神！

vue的官方文档中写Vuex 来管理组件的状态，我自己的理解是当Vuex中的数据发生变化，vue都能监视到，从而更新视图localStorage中的数据发生变化，vue不能对视图进行及时的更新，像保持登陆的数据，因为要让视图更新和持久保存，我就在localStorage里也放了一份，其实现在想想，只放在localStorage不放在Vuex中，好像也没什么影响。毕竟登陆后获取的用户数据不会经常改变。
