### ISSUE TITLE
网上搜索10篇文章，写法都不一样，我擦

### ISSUE THREAD

**Issue by fengjinqi** [PuZhiweizuishuai/SpringSecurity-JWT-Vue-Deom#6]
兄弟，你的UserDetailsService实现接口在哪儿呢？能不能来个正常的0到1实现，从数据库，controller，service impl 实现

**Comment by PuZhiweizuishuai** [comment]
> 兄弟，你的UserDetailsService实现接口在哪儿呢？能不能来个正常的0到1实现，从数据库，controller，service impl 实现

https://github.com/PuZhiweizuishuai/SpringSecurity-JWT-Vue-Deom/blob/master/spring-security-jwt/src/main/java/com/bugaugaoshu/security/config/CustomUserDetailsService.java#L17
